name: Release
on:  
  release:
    types: 
      - created # This triggers once you create a release from github, not from tagging a commit
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build gbdk project
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Build
      uses: wujood/gbdk-2020-github-builder@1.0.5
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./mainC.gb # Result file from build is called game.gb by default. Rename it with the output-name parameter.
        asset_name: ROM # Rename this to what ever you want
        tag: ${{ github.ref }}